(defconst fpc-all-reserved-words
  '(

    ;; 'font-lock-keyword-face
(regexp-opt '(
    "asm"
    "begin"
    "case"
    "class"
    "define"
    "do"
    "downto"
    "else"
    "end"
    "extern"
    "external"
    "finalization"
    "for"
    "forward"
    "function"
    "goto"
    "if"
    "implementation"
    "initialization"
    "input"
    "interface"
    "label"
    "module"
    "otherwise"
    "output"
    "private"
    "procedure"
    "program"
    "public"
    "repeat"
    "static"
    "then"
    "to"
    "unit"
    "until"
    "uses"
    "while"
    "with") t)
"\\(asm\\|begin\\|c\\(?:ase\\|lass\\)\\|d\\(?:efine\\|o\\(?:wnto\\)?\\)\\|e\\(?:lse\\|nd\\|xtern\\(?:al\\)?\\)\\|f\\(?:inalization\\|or\\(?:ward\\)?\\|unction\\)\\|goto\\|i\\(?:f\\|mplementation\\|n\\(?:itialization\\|put\\|terface\\)\\)\\|label\\|module\\|o\\(?:therwise\\|utput\\)\\|p\\(?:r\\(?:ivate\\|o\\(?:cedure\\|gram\\)\\)\\|ublic\\)\\|repeat\\|static\\|t\\(?:hen\\|o\\)\\|u\\(?:n\\(?:it\\|til\\)\\|ses\\)\\|w\\(?:hile\\|ith\\)\\)"

(regexp-opt '(
              "!"
              "*"
              "+"
              "-"
              "/"
              ":="
              "="
              "@"
              "^"
              "and"
              "div"
              "mod"
              "not"
              "or"
              ) t)
"\\(:=\\|and\\|div\\|mod\\|not\\|or\\|[!*+/=@^-]\\)"





    ;; 'font-lock-type-face
(regexp-opt '(
    "array"
    "const"
    "file"
    "packed"
    "record"
    "set"
    "type"
    "var"))
"\\(?:array\\|const\\|file\\|packed\\|record\\|set\\|type\\|var\\)"


    ;; 'font-lock-builtin-face
(regexp-opt '(
    "abs"
    "and"
    "arctan"
    "boolean"
    "char"
    "chr"
    "close"
    "cos"
    "dispose"
    "div"
    "eof"
    "eoln"
    "exit"
    "exp"
    "false"
    "get"
    "in"
    "integer"
    "ln"
    "main"
    "maxint"
    "minint"
    "mod"
    "new"
    "nil"
    "not"
    "odd"
    "of"
    "open"
    "or"
    "ord"
    "pred"
    "put"
    "read"
    "readln"
    "real"
    "reset"
    "result"
    "rewrite"
    "round"
    "sin"
    "sqr"
    "sqrt"
    "succ"
    "tan"
    "text"
    "true"
    "trunc"
    "write"
    "writeln") t)
"\\(a\\(?:bs\\|nd\\|rctan\\)\\|boolean\\|c\\(?:h\\(?:a?r\\)\\|lose\\|os\\)\\|di\\(?:spose\\|v\\)\\|e\\(?:o\\(?:f\\|ln\\)\\|x\\(?:it\\|p\\)\\)\\|false\\|get\\|in\\(?:teger\\)?\\|ln\\|m\\(?:a\\(?:in\\|xint\\)\\|inint\\|od\\)\\|n\\(?:ew\\|il\\|ot\\)\\|o\\(?:dd\\|pen\\|rd\\|[fr]\\)\\|p\\(?:red\\|ut\\)\\|r\\(?:e\\(?:a\\(?:dln\\|[dl]\\)\\|s\\(?:\\(?:e\\|ul\\)t\\)\\|write\\)\\|ound\\)\\|s\\(?:in\\|qrt?\\|ucc\\)\\|t\\(?:an\\|ext\\|ru\\(?:e\\|nc\\)\\)\\|write\\(?:ln\\)?\\)"



    ))
